package com.bloodnetwork.bangladesh.ui.navigation

object Routes {
    const val LANDING = "landing"
    const val LOGIN = "login"
    const val REGISTER = "register"
    const val FIND_BLOOD = "find_blood"
    const val REQUEST_BLOOD = "request_blood"
    const val MY_REQUESTS = "my_requests"
    const val MY_MATCHES = "my_matches"
    const val REQUEST_DETAILS = "request_details"
    const val ELIGIBILITY = "eligibility"
    const val NOTIFICATIONS = "notifications"
    const val DONOR_DASHBOARD = "donor_dashboard"
    const val DONOR_PROFILE = "donor_profile"
    const val CHATBOT = "chatbot"
    const val EDIT_PROFILE = "edit_profile"
    const val ADMIN_DASHBOARD = "admin_dashboard"
    const val ADMIN_ANALYTICS = "admin_analytics"
    const val ADMIN_USERS = "admin_users"
    const val ADMIN_REPORTS = "admin_reports"
    const val ADMIN_BLOOD_REQUESTS = "admin_blood_requests"
    const val ADMIN_MATCHES = "admin_matches"
    const val ADMIN_AUDIT_LOGS = "admin_audit_logs"
    const val ADMIN_SETTINGS = "admin_settings"
    const val ADMIN_ELIGIBILITY_QUESTIONS = "admin_eligibility_questions"
    const val ABOUT = "about"
}
